**Create a NumPy array of integers from 1 to 10.**

In [ ]:
import numpy as np

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Create a 2x3 NumPy array filled with zeros.**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Create a NumPy array of even numbers from 2 to 20.**

In [ ]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.**

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

**Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.**

In [ ]:
arr4=np.random.rand(100)
arr4

array([0.87754817, 0.91505109, 0.80809788, 0.50768655, 0.21660855,
       0.08071887, 0.66496276, 0.37280755, 0.90984565, 0.83542655,
       0.67868072, 0.61993799, 0.4752839 , 0.26521206, 0.01668566,
       0.69742153, 0.06480714, 0.22766463, 0.73683632, 0.0041499 ,
       0.23861241, 0.22199845, 0.86067997, 0.44538953, 0.64594145,
       0.6004498 , 0.02917057, 0.15060738, 0.05088884, 0.3086813 ,
       0.04982493, 0.88516819, 0.29143134, 0.05663712, 0.73740369,
       0.20687725, 0.47155024, 0.2369323 , 0.49218926, 0.75117228,
       0.97143888, 0.57981167, 0.71562391, 0.77799482, 0.52033627,
       0.88512019, 0.56641661, 0.29290056, 0.80142566, 0.81478818,
       0.87269909, 0.50828264, 0.91879344, 0.80983145, 0.2473262 ,
       0.15521354, 0.61707725, 0.84801728, 0.65150168, 0.22698899,
       0.11452807, 0.54683633, 0.85002458, 0.82440186, 0.4323279 ,
       0.58183008, 0.59456655, 0.78012164, 0.15631318, 0.11390202,
       0.08617041, 0.60346133, 0.91017345, 0.27271693, 0.01180

In [ ]:
arr4=arr4.mean()
arr4

0.50351953709671

**Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4)**

In [ ]:
arr4=np.random.randint(0,20,12)

In [ ]:
arr4

array([ 5,  6, 11,  3, 17, 16, 13, 14,  0,  4, 15, 19])

In [ ]:
arr5=arr4.reshape(3,4)
arr5

array([[ 5,  6, 11,  3],
       [17, 16, 13, 14],
       [ 0,  4, 15, 19]])

**Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in the array using NumPy functions.**

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

**Create a 5x5 identity matrix using NumPy.**

In [ ]:
arr=np.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6])**

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
a.dot(b)

32

**Find the index of the maximum value and the index of the minimum value
in a NumPy array.**

In [ ]:
a=np.array([4,5,6,7])

In [ ]:
a

array([4, 5, 6, 7])

In [ ]:
a.argmax()

3

In [ ]:
a.argmin()

0

**Concatenate two random NumPy arrays horizontally and vertically**

In [ ]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print("vertical concatenate-\n",c)
print("horizontal concatenate-\n",d)

vertical concatenate-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenate-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


**Given a 2D NumPy array, calculate the sum of each row and each column
separately.**

In [ ]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("sum of each colum is",np.sum(arr,axis=0))
print("sum of each row is",np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each colum is [28 32 36 40]
sum of each row is [10 26 42 58]


**Find the common elements between two NumPy arrays.**

In [ ]:
a=np.array([[3,2],[5,6],[1,7]])
b=np.array([[3,1],[5,4],[0,8]])
c=np.intersect1d(a,b)
print("The common element between a and b are",c)

The common element between a and b are [1 3 5]


**Replace all negative values in a NumPy array with zeros.**

In [ ]:
a=np.array([1,2,3,-4,-5])
a[a<0]=0
a

array([1, 2, 3, 0, 0])

**Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.**

In [ ]:
arr=np.random.randint(0,101,100)
arr.sort()
arr

array([  0,   0,   1,   3,   3,   3,   4,   5,   9,  11,  13,  14,  14,
        15,  15,  17,  17,  18,  19,  20,  21,  21,  23,  24,  25,  26,
        31,  31,  31,  32,  34,  36,  36,  38,  39,  41,  42,  42,  43,
        44,  44,  48,  48,  49,  49,  50,  50,  51,  51,  51,  53,  53,
        53,  54,  55,  56,  57,  58,  58,  60,  61,  61,  61,  62,  65,
        65,  65,  66,  67,  68,  69,  70,  73,  75,  77,  78,  83,  84,
        85,  86,  88,  89,  89,  90,  90,  91,  93,  93,  93,  95,  95,
        95,  95,  97,  98,  98,  99,  99, 100, 100])

**Calculate the element-wise absolute difference between two NumPy
arrays.**

In [ ]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,8])
c=np.absolute(a-b)
print(c)

[1 2 3 4]


**Given a 2D NumPy array, extract the first row and the last column.**

In [ ]:
arr=np.array([[1,2,4],[3,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("first row is\n",firstrow)
print("late colum is\n",lastcol)

first row is
 [1 2 4]
late colum is
 [[4]
 [6]
 [9]]


**Slice a 1D NumPy array to get every other element.**

In [ ]:
a=np.array([1,2,3,4])
x=a[0:len(a)+1]
print(x)

[1 2 3 4]


**9.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.**

In [ ]:
arr=np.array([[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,44,45,46],[51,52,53,54,55,56]])
a=arr[2:4,[2,3]]
print("array\n",arr)
print("2x2 array\n",a)

array
 [[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]]
2x2 array
 [[33 34]
 [43 44]]


**Reverse a 1D NumPy array using slicing**

In [ ]:
a=np.array([1,2,3,4])
x=a[::-1]
x

array([4, 3, 2, 1])